import { NextUIProvider } from '@/contexts/NextUIProvider/NextUIProvider'
import { Roboto } from 'next/font/google'

import '@/styles/globals.scss'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const roboto = Roboto({
  weight: [
    '300',
    '400',
    '500',
    '700'
  ],
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NextUIProvider>
          {children}
        </NextUIProvider>
      </body>
    </html>
  )
}
