import { NextUIProvider } from '@/contexts/NextUIProvider/NextUIProvider'
import { Roboto, Work_Sans } from 'next/font/google'

import '@/styles/globals.scss'
import classNames from 'classnames'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const roboto = Roboto({
  weight: [
    '300',
    '400',
    '500',
    '700'
  ],
  subsets: ['latin'],
})

const workSans = Work_Sans({
  variable: '--font-work-sans',
  subsets: ['latin'],
  weight: [
    '700'
  ]
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={classNames(roboto.className, workSans.variable)}>
        <NextUIProvider>
          {children}
        </NextUIProvider>
      </body>
    </html>
  )
}
