import { NextUIProvider } from '@/contexts/NextUIProvider/NextUIProvider'
import { Roboto, Work_Sans } from 'next/font/google'
import localFont from 'next/font/local'

import '@/styles/globals.scss'
import clsx from 'clsx'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const roboto = Roboto({
  weight: [
    '300',
    '400',
    '500',
    '700'
  ],
  subsets: ['latin'],
})

const workSans = Work_Sans({
  variable: '--font-work-sans',
  subsets: ['latin'],
  weight: [
    '700'
  ]
})

const sofiaProSoft = localFont({
  variable: '--font-sofia-pro-soft',
  src: [
    {
      path: '../fonts/SofiaProSoft/SofiaProSoftReg.otf',
      weight: '400'
    },
    {
      path: '../fonts/SofiaProSoft/SofiaProSoftBold.otf',
      weight: '700'
    }
  ]
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(roboto.className, workSans.variable, sofiaProSoft.variable)}>
        <NextUIProvider>
          {children}
        </NextUIProvider>
      </body>
    </html>
  )
}
