# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  helm: circleci/helm@3.0.0
  kubernetes: circleci/kubernetes@1.3.1


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  pre-deploy:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
    - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
    - checkout
    - kubernetes/install-kubeconfig:
        kubeconfig: KUBECONFIG_DATA
    - kubernetes/install-kubectl
    - helm/install_helm_client
    - run:
        name: Setup k8s cluster
        command: kubectl get pod

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows

workflows:
  main-workflow:
    jobs:
    - pre-deploy
