# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  helm: circleci/helm@3.0.0
  kubernetes: circleci/kubernetes@1.3.1

commands:
  setup-k8s:
    steps:
    - kubernetes/install-kubeconfig:
        kubeconfig: KUBECONFIG_DATA
    - run:
        name: Fix kubeconfig permissions
        command: chmod go-r ~/.kube/config
    - kubernetes/install-kubectl
    - helm/install_helm_client
    - helm/install_helm_plugin:
        helm_plugin_url: https://github.com/databus23/helm-diff
    - run:
        name: Install ingress-nginx
        command: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install ingress-nginx-release ingress-nginx/ingress-nginx -n ingress-nginx --create-namespace || true
  setup-docker:
    steps:
    - setup_remote_docker:
        docker_layer_caching: true
  push-image:
    parameters:
      image-context:
        type: string
      image-path:
        type: string
      image-name:
        type: string
    steps:
    - run:
        name: Build Docker image
        command: |
          docker build \
            -t $GITHUB_USERNAME/<<parameters.image-name>>:$CIRCLE_BRANCH \
            -f <<parameters.image-path>> \
            <<parameters.image-context>>
    - run:
        name: Push Docker image
        command: |
          echo $CR_PAT
          IMAGE_ID=$(docker images -q $GITHUB_USERNAME/<<parameters.image-name>>:$CIRCLE_BRANCH)
          IMAGE_TAG=ghcr.io/$GITHUB_USERNAME/<<parameters.image-name>>:$CIRCLE_BRANCH
          echo $CR_PAT | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
          docker tag $IMAGE_ID $IMAGE_TAG
          docker push $IMAGE_TAG

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  deploy-frontend:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
    - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
    - checkout
    - setup-k8s
    - setup-docker
    - push-image:
        image-context: .
        image-path: ./k8s/frontend/docker/build.Dockerfile
        image-name: ch-frontend
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows

workflows:
  main-workflow:
    jobs:
    - deploy-frontend
