controller:
  hostNetwork: true
  service:
    externalTrafficPolicy: Local
  ingressClassResource:
    enabled: true
    default: true
  config:
    # whitelist-source-range: 192.168.1.51/32
    syslog-endpoint: stdout
    syslog-format: raw
    forwardfor: update
  haproxy:
    enabled: true
    securityContext:
      runAsUser: 0
