version: '3'

volumes:
  dragonflydata:

services:
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - 6379:6379
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
        - ./data/db:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password