version: '3'

volumes:
  dragonflydata:

services:
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
        - ./init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
        - ./data/db:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: api_password
      POSTGRES_DB: api_db
      POSTGRES_CRM_USER: crm_user
      POSTGRES_CRM_PASSWORD: crm_password
      POSTGRES_CRM_DB: crm_db
