apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
  labels:
    app: nextjs
spec:
  replicas: 1 # TODO: scale smartly
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      {{- if hasKey .Values.frontend.image "pullSecrets" }}
      imagePullSecrets:
        - name: {{ .Values.frontend.image.pullSecrets.name }}
      {{- end }}
      containers:
        - name: nextjs-container
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          image: {{ .Values.frontend.image.name }}
          resources:
            limits: # TODO: tune those values for best efficiency
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 3000
              name: nextjs-port
          
