apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-ingress
  annotations:
    {{- if ((.Values.ingress).whitelistSourceRange) }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.ingress.whitelistSourceRange }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: nextjs-service
                port:
                  number: 80
            path: /
