apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-ingress
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 82.65.5.17/32
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.frontend.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: nextjs-service
                port:
                  number: 80
            path: /