apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  externalTrafficPolicy: Local
  type: NodePort
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: nextjs-port
