apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nestjs-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.api.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: nestjs-service
                port:
                  number: 80
            path: /