apiVersion: v1
kind: Secret
metadata:
  name: nestjs-secret
type: Opaque
data:
  {{- range $key, $value := .Values.nestjs.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  {{- range $key, $value := .Values.postgres.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}